# ============================================================
# Configuration specifique a api-gateway
# Servi uniquement quand spring.application.name=api-gateway
# ============================================================

server.port=8080

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/members/**


logging.level.org.springframework.cloud.gateway=DEBUG
