server:
  port: 9000
spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/members/**
            - id: supervision-service
              uri: lb://supervision-service
              predicates:
                - Path=/api/v1/topics/**, /api/v1/requests/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG