eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/researchhub

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

  endpoint:
    health:
      show-details: always
