server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/authdb
    username: authuser
    password: authpass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    com.researchhub: DEBUG
