# ============================================================
# Configuration specifique a auth-service
# Servi uniquement quand spring.application.name=auth-service
# ============================================================

server.port=8086

# --- Database ---
spring.datasource.url=jdbc:postgresql://localhost:5434/authdb
spring.datasource.username=authuser
spring.datasource.password=authpass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate


# --- Liquibase ---
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# --- OAuth2 / Keycloak security ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/researchhub

# --- Logging ---
logging.level.com.researchhub=DEBUG
